# Generated by Django 5.2.17 on 2026-09-29 02:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('ACCOUNT', 'Account'), ('ADDRESS', 'Address')], max_length=16)),
                ('key_hash', models.CharField(max_length=64)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'locked_until'], name='accounts_lo_scope_390e96_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='uq_login_throttle_scope_key')],
            },
        ),
    ]
