# Generated by Django 5.2.17 on 2026-09-29 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginthrottle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, max_length=2000)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_audit_events', to='accounts.accountauditevent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_audit_history', to='accounts.accountauditevent')),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'created_at'], name='accounts_ac_target__4f5ef0_idx'), models.Index(fields=['actor', 'created_at'], name='accounts_ac_actor_i_035b23_idx')],
            },
        ),
    ]
