# Generated by Django 5.2.17 on 2026-09-29 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountauditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauditevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountauditevent',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_audit_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
