# Generated by Django 5.2.17 on 2026-09-29 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('scheduled_for', models.DateTimeField()),
                ('observation_started_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('timezone', models.CharField(max_length=64)),
                ('scope_board_ids', models.JSONField(default=list)),
                ('definition_version', models.PositiveIntegerField(default=1)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('rows', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('delayed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('revised_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='reports.reportsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'report_date', 'generated_at'], name='reports_rep_recipie_834634_idx')],
            },
        ),
    ]
