# Generated by Django 5.2.17 on 2026-09-29 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workitems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_key', models.CharField(max_length=255, unique=True)),
                ('job_type', models.CharField(max_length=64)),
                ('run_after', models.DateTimeField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('LEASED', 'Leased'), ('SENDING', 'Sending'), ('SUCCEEDED', 'Succeeded'), ('RETRY_WAIT', 'Retry wait'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed'), ('UNKNOWN', 'Unknown')], default='READY', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'run_after'], name='notificatio_status_2774d6_idx'), models.Index(fields=['lease_expires_at'], name='notificatio_lease_e_141fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_key', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(max_length=64)),
                ('scheduled_for', models.DateTimeField()),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DRY_RUN', 'Dry run'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Suppressed'), ('UNKNOWN', 'Unknown')], default='QUEUED', max_length=16)),
                ('destination_generation', models.PositiveIntegerField(default=1)),
                ('message_preview', models.TextField(blank=True, max_length=3000)),
                ('conversation_id', models.CharField(blank=True, max_length=128)),
                ('message_ts', models.CharField(blank=True, max_length=128)),
                ('attempt_uuid', models.UUIDField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='workitems.task')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'status', 'scheduled_for'], name='notificatio_recipie_9f4cb3_idx'), models.Index(fields=['task', 'kind'], name='notificatio_task_id_4921d4_idx')],
            },
        ),
    ]
