# Generated by Django 5.2.17 on 2026-09-29 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField()),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='report_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='reports.reportsnapshot'),
        ),
        migrations.CreateModel(
            name='SlackPilotApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_generation', models.PositiveIntegerField()),
                ('sample_hash', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slack_pilot_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'active'], name='notificatio_recipie_197869_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'destination_generation'), name='uq_slack_pilot_recipient_generation')],
            },
        ),
    ]
