from __future__ import annotations

from datetime import timedelta
from typing import Any
from zoneinfo import ZoneInfo

from boards.models import Board, BoardColumn, BoardMembership
from core.clock import now
from django.db import transaction
from django.db.models import Max
from notifications.jobs import enqueue_job
from workitems.models import AuditEvent, ChecklistItem, CommitmentRevision, Task

from .engine import PreviewOccurrence, generate_due_occurrences
from .models import Occurrence, Schedule, ScheduleRevision


def _pause_values(schedule: Schedule, through_date) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for row in schedule.pauses.order_by("start_base_date"):
        end = row.end_base_date or (through_date + timedelta(days=1))
        result.append({"start": row.start_base_date.isoformat(), "end": end.isoformat()})
    return result


def _is_paused(occurrence: PreviewOccurrence, pauses: list[dict[str, str]]) -> bool:
    key = occurrence.base_release_date.isoformat()
    return any(item["start"] <= key < item["end"] for item in pauses)


def _active_owner(board: Board, owner_id: str) -> bool:
    return BoardMembership.objects.filter(
        board=board,
        user_id=owner_id,
        is_active=True,
        user__is_active=True,
    ).exists()


def _column(board: Board, state: str) -> BoardColumn:
    return BoardColumn.objects.get(board=board, state=state, is_archived=False)


def _next_position(column: BoardColumn) -> int:
    current = Task.objects.filter(
        column=column,
        is_cancelled=False,
        is_archived=False,
    ).aggregate(
        value=Max("position")
    )["value"]
    return int(current or -1) + 1


def _audit(
    *, board: Board, task: Task, actor, action: str, reason: str, after: dict[str, Any]
) -> None:
    board.revision += 1
    board.save(update_fields=["revision", "updated_at"])
    AuditEvent.objects.create(
        board=board,
        board_revision=board.revision,
        task=task,
        actor=actor,
        action=action,
        reason=reason,
        before={},
        after=after,
    )


def _create_committed_occurrence(
    *,
    schedule: Schedule,
    revision: ScheduleRevision,
    occurrence: PreviewOccurrence,
) -> Task:
    template = revision.template_fields
    owner_id = str(template["owner_id"])
    board = schedule.board
    todo = _column(board, BoardColumn.State.TODO)
    task = Task.objects.create(
        board=board,
        column=todo,
        title=str(template["title"]),
        description=str(template.get("description", "")),
        priority=int(template["priority"]),
        current_owner_id=owner_id,
        original_owner_id=owner_id,
        position=_next_position(todo),
        committed_at=now(),
        created_by=revision.actor,
    )
    checklist_rows = [
        ChecklistItem(task=task, text=text, required=True, position=index, checked=False)
        for index, text in enumerate(template.get("required_checklist", []))
    ]
    if checklist_rows:
        ChecklistItem.objects.bulk_create(checklist_rows)

    commitment = CommitmentRevision.objects.create(
        task=task,
        revision=1,
        owner_id=owner_id,
        due_at=occurrence.due_at,
        priority=int(template["priority"]),
        acceptance_criteria=str(template["acceptance_criteria"]),
        required_checklist_snapshot=[
            {"text": item.text, "required": True, "position": item.position}
            for item in checklist_rows
        ],
        actor=revision.actor,
        reason=f"Generated by schedule {schedule.id} period {occurrence.period_key}",
    )
    task.current_commitment = commitment
    task.save(update_fields=["current_commitment", "updated_at"])
    Occurrence.objects.create(
        schedule=schedule,
        period_key=occurrence.period_key,
        schedule_revision=revision,
        task=task,
        release_at=occurrence.release_at,
        due_at=occurrence.due_at,
    )
    _audit(
        board=board,
        task=task,
        actor=revision.actor,
        action="generate_recurring_task",
        reason=f"Schedule period {occurrence.period_key}",
        after={
            "schedule_id": str(schedule.id),
            "period_key": occurrence.period_key,
            "due_at": occurrence.due_at.isoformat(),
        },
    )
    from notifications.obligations import schedule_commitment_notifications

    schedule_commitment_notifications(task)
    return task


def _create_needs_assignment(
    *,
    schedule: Schedule,
    revision: ScheduleRevision,
    occurrence: PreviewOccurrence,
) -> Task:
    template = revision.template_fields
    board = schedule.board
    backlog = _column(board, BoardColumn.State.BACKLOG)
    task = Task.objects.create(
        board=board,
        column=backlog,
        title=str(template["title"]),
        description=(
            str(template.get("description", ""))
            + "\n\n[Automation exception: intended owner unavailable; manager assignment required.]"
        )[:20000],
        priority=int(template["priority"]),
        current_owner=None,
        original_owner_id=template.get("owner_id"),
        position=_next_position(backlog),
        draft_due_at=occurrence.due_at,
        draft_acceptance_criteria=str(template["acceptance_criteria"]),
        created_by=revision.actor,
    )
    Occurrence.objects.create(
        schedule=schedule,
        period_key=occurrence.period_key,
        schedule_revision=revision,
        task=task,
        release_at=occurrence.release_at,
        due_at=occurrence.due_at,
    )
    _audit(
        board=board,
        task=task,
        actor=revision.actor,
        action="recurrence_owner_unavailable",
        reason="Intended schedule owner is not an active board member.",
        after={
            "schedule_id": str(schedule.id),
            "period_key": occurrence.period_key,
            "intended_due_at": occurrence.due_at.isoformat(),
        },
    )
    manager_ids = list(
        BoardMembership.objects.filter(
            board=board,
            role=BoardMembership.Role.MANAGER,
            is_active=True,
            user__is_active=True,
        ).values_list("user_id", flat=True)
    )
    for manager_id in manager_ids:
        enqueue_job(
            semantic_key=f"needs-assignment:{task.id}:{manager_id}",
            job_type="needs_assignment",
            run_after=now(),
            payload={"task_id": str(task.id), "recipient_id": str(manager_id)},
            generation=schedule.generation,
        )
    return task


def generate_schedule_batch(schedule_id, *, limit: int = 100) -> dict[str, Any]:
    observed_at = now()
    created: list[str] = []
    skipped_paused: list[str] = []
    with transaction.atomic():
        schedule_info = Schedule.objects.only("board_id").get(pk=schedule_id)
        board = Board.objects.select_for_update().get(pk=schedule_info.board_id)
        schedule = (
            Schedule.objects.select_for_update(of=("self",))
            .select_related("current_revision", "board")
            .get(pk=schedule_id)
        )
        if not schedule.active or schedule.current_revision is None or board.archived:
            return {
                "created": [],
                "skipped_paused": [],
                "cursor": schedule.cursor_period_key,
            }

        revisions = list(
            schedule.revisions.select_for_update().order_by(
                "effective_base_period",
                "revision",
            )
        )
        local_date = observed_at.astimezone(ZoneInfo(schedule.timezone)).date()
        pauses = _pause_values(schedule, local_date)
        owned_candidates: list[tuple[PreviewOccurrence, ScheduleRevision]] = []
        for index, revision in enumerate(revisions):
            next_boundary = (
                revisions[index + 1].effective_base_period if index + 1 < len(revisions) else None
            )
            candidates = generate_due_occurrences(
                dict(revision.rule),
                through=observed_at,
                after_period_key=schedule.cursor_period_key,
                limit=limit,
                pauses=None,
            )
            for occurrence in candidates:
                if occurrence.period_key < revision.effective_base_period:
                    continue
                if next_boundary is not None and occurrence.period_key >= next_boundary:
                    continue
                owned_candidates.append((occurrence, revision))

        owned_candidates.sort(key=lambda item: item[0].period_key)
        selected = owned_candidates[:limit]
        for occurrence, revision in selected:
            if Occurrence.objects.filter(
                schedule=schedule,
                period_key=occurrence.period_key,
            ).exists():
                schedule.cursor_period_key = occurrence.period_key
                continue
            if _is_paused(occurrence, pauses):
                skipped_paused.append(occurrence.period_key)
            else:
                owner_id = str(revision.template_fields["owner_id"])
                task = (
                    _create_committed_occurrence(
                        schedule=schedule,
                        revision=revision,
                        occurrence=occurrence,
                    )
                    if _active_owner(board, owner_id)
                    else _create_needs_assignment(
                        schedule=schedule,
                        revision=revision,
                        occurrence=occurrence,
                    )
                )
                created.append(str(task.id))
            schedule.cursor_period_key = occurrence.period_key

        if selected:
            schedule.save(update_fields=["cursor_period_key"])
    return {
        "created": created,
        "skipped_paused": skipped_paused,
        "cursor": schedule.cursor_period_key,
    }
