# Generated by Django 5.2.17 on 2026-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcolumn',
            name='state',
            field=models.CharField(choices=[('BACKLOG', 'Inbox'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Later'), ('REVIEW', 'Review (legacy)'), ('DONE', 'Done')], max_length=32),
        ),
    ]
