# Generated by Django 5.2.17 on 2026-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_global_board_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
