# Generated by Django 5.2.17 on 2026-10-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_boardcolumn_is_custom_alter_boardcolumn_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
