# Generated by Django 5.2.17 on 2026-10-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_boardcolumn_archived_at_boardcolumn_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
