# Generated by Django 5.2.17 on 2026-10-07 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_LABEL_COLORS = ["green", "yellow", "orange", "red", "purple", "blue"]


def seed_default_labels(apps, schema_editor):
    Board = apps.get_model("boards", "Board")
    BoardLabel = apps.get_model("boards", "BoardLabel")
    rows = []
    for board in Board.objects.all().iterator():
        for position, color in enumerate(DEFAULT_LABEL_COLORS):
            rows.append(
                BoardLabel(
                    board_id=board.id,
                    color=color,
                    position=position,
                    name="",
                    description="",
                )
            )
    if rows:
        BoardLabel.objects.bulk_create(rows)


def remove_seeded_labels(apps, schema_editor):
    BoardLabel = apps.get_model("boards", "BoardLabel")
    BoardLabel.objects.filter(name="", description="", color__in=DEFAULT_LABEL_COLORS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_boardcolumn_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.FileField(blank=True, upload_to='board_backgrounds/'),
        ),
        migrations.AddField(
            model_name='board',
            name='background_key',
            field=models.CharField(blank=True, default='rainbow', max_length=32),
        ),
        migrations.CreateModel(
            name='BoardLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['board', 'position'], name='boards_boar_board_i_ca078b_idx')],
            },
        ),
        migrations.RunPython(seed_default_labels, remove_seeded_labels),
    ]
