# Generated by Django 5.2.17 on 2026-09-29 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('workitems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('cursor_period_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='boards.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('rule', models.JSONField(default=dict)),
                ('template_fields', models.JSONField(default=dict)),
                ('effective_base_period', models.CharField(max_length=64)),
                ('reason', models.TextField(max_length=2000)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='schedules.schedule')),
            ],
            options={
                'ordering': ['schedule_id', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schedules.schedulerevision'),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=64)),
                ('release_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence', to='workitems.task')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='schedules.schedule')),
                ('schedule_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='schedules.schedulerevision')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_base_date', models.DateField()),
                ('end_base_date', models.DateField()),
                ('reason', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to='schedules.schedule')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_base_date__gt', models.F('start_base_date'))), name='schedule_pause_end_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedulerevision',
            constraint=models.UniqueConstraint(fields=('schedule', 'revision'), name='uq_schedule_revision'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['schedule', 'period_key'], name='schedules_o_schedul_01cd6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(fields=('schedule', 'period_key'), name='uq_schedule_period'),
        ),
    ]
