# Generated by Django 5.2.17 on 2026-09-29 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedulepause',
            name='schedule_pause_end_after_start',
        ),
        migrations.AlterField(
            model_name='schedulepause',
            name='end_base_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='schedulepause',
            constraint=models.CheckConstraint(condition=models.Q(('end_base_date__isnull', True), ('end_base_date__gt', models.F('start_base_date')), _connector='OR'), name='schedule_pause_end_after_start'),
        ),
    ]
