# Generated by Django 5.2.17 on 2026-09-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='draft_acceptance_criteria',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='task',
            name='draft_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
