# Generated by Django 5.2.17 on 2026-09-29 05:05

import core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0002_task_draft_acceptance_criteria_task_draft_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(default=core.clock.now, editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(default=core.clock.now, editable=False),
        ),
    ]
