# Generated by Django 5.2.17 on 2026-09-30 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_global_board_access'),
        ('workitems', '0003_alter_review_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_frequency',
            field=models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_generation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_next_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['recurrence_frequency', 'recurrence_next_at'], name='workitems_recurrence_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_generation__gte', 1)), name='task_recurrence_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_anchor_day__isnull', True), models.Q(('recurrence_anchor_day__gte', 1), ('recurrence_anchor_day__lte', 31)), _connector='OR'), name='task_recurrence_anchor_day_1_31'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence_frequency', 'NONE'), ('recurrence_next_at__isnull', True)), models.Q(models.Q(('recurrence_frequency', 'NONE'), _negated=True), ('recurrence_next_at__isnull', False)), _connector='OR'), name='task_recurrence_configuration_valid'),
        ),
    ]
