# Generated by Django 5.2.17 on 2026-10-06 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_boardcolumn_archived_at_boardcolumn_color_and_more'),
        ('workitems', '0004_task_recurrence_anchor_day_task_recurrence_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='uq_active_task_position',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='workitems_t_current_d134ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='workitems_t_priorit_ab3a9a_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['current_owner', 'is_cancelled', 'is_archived'], name='workitems_t_current_ccd761_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'is_cancelled', 'is_archived'], name='workitems_t_priorit_51fb41_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('is_cancelled', False)), fields=('column', 'position'), name='uq_active_task_position'),
        ),
    ]
