# Generated by Django 5.2.17 on 2026-10-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_board_background_image_board_background_key_and_more'),
        ('workitems', '0005_remove_task_uq_active_task_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='boards.boardlabel'),
        ),
    ]
